{
  "comments": [
    {
      "key": {
        "uuid": "1f2383d7_1dae9f35",
        "filename": "src/dawn_native/Device.cpp",
        "patchSetId": 5
      },
      "lineNbr": 119,
      "author": {
        "id": 1000308
      },
      "writtenOn": "2020-03-27T18:13:38Z",
      "side": 1,
      "message": "Should we be ignoring all errors here, not just device loss ? Since this is the internal error type?",
      "revId": "3296a3edef8fea228fbce642b27ecb86fb2988a2",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "eadd94a9_7413d348",
        "filename": "src/dawn_native/Device.cpp",
        "patchSetId": 5
      },
      "lineNbr": 119,
      "author": {
        "id": 1000002
      },
      "writtenOn": "2020-03-27T18:16:58Z",
      "side": 1,
      "message": "Ideally not, because Internal errors should be programming issues in Dawn, so we want to ASSERT on them.",
      "parentUuid": "1f2383d7_1dae9f35",
      "revId": "3296a3edef8fea228fbce642b27ecb86fb2988a2",
      "serverId": "dd02978d-1a8e-36d7-bcc0-a5723e5c0abd",
      "unresolved": true
    }
  ]
}